### PR TITLE
Pr 1618

### PR DESCRIPTION
**Pull request by kurtnordstrom**

### CODE REVIEW

**Review by skomorokh — APPROVED** [review]
Nice, quite a chunk of work. 

- I like the reuse of some of the new request stuff and hope we can do a bit more there in future (it feels like request validation broadly ought to be its own overall operation). 
- Glad this got its own file.
- I wonder about the naming, eg. this is actually the digital non-returnables state model, but w/e it happened first so maybe physical just inherits and extends it and we draw the distinction there.

**Comment by MikeTaylor** [comment]
Just noting my concern at how we seem to be conflating request _type_ (loan or copy) what _what_ is being requested (book or article). I feel like I've been nudged into writing code in the OpenURL resolver that assumes copy requests are inherently for articles and loan requests are inherently for books. I don't think either is necessarily true.

**Comment by skomorokh** [comment]
How so Mike? The non-returnable state model is chosen based on a serviceType of copy so it should be entirely possible to use it regardless of the publicationType: https://github.com/openlibraryenvironment/mod-rs/pull/665/files#diff-62dd633217190073a0aa1ff952baea306e718f81c5aef11ce3bb880fa3cced16R513

**Comment by MikeTaylor** [comment]
> How so Mike? The non-returnable state model is chosen based on a serviceType of copy so it should be entirely possible to use it regardless of the publicationType.

Good, I am glad this confusion doesn't manifest in mod-rs, where it really matters. Hopefully the confusion I was referring to is only in the resolver and its forms.

**Pull request merged**
